[package]
name = "ls_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
nalgebra = { version = "0.32.2", features = ["io", "sparse"] }
nalgebra-sparse = { version = "0.9.0", features = ["io"] }
